version: "3.3"

services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - flyttilfavrskov:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=$DATABASE_NAME
      - MYSQL_USER=$DATABASE_USER
      - MYSQL_PASSWORD=$DATABASE_PASS
      - MYSQL_ROOT_PASSWORD=$DATABASE_ROOT
    restart: always
    ports:
      - "3306:3306"

  app:
    image: flyttilfavrskov_app:dev
    build:
      context: .
      args:
        current_env: $ENV
        sites_folder: $SITES_FOLDER
    depends_on:
      - database
    environment:
      - DDS_DOCKER=true
      - APP_ENV=$ENV
      - DB_HOST=database
      - DB_NAME=$DATABASE_NAME
      - DB_USER=$DATABASE_USER
      - DB_PASS=$DATABASE_PASS
      - DB_PORT=3306
      - DOMAIN=$LOCAL_DOMAIN
      - SITES_FOLDER=$SITES_FOLDER
    ports:
      - "80:80"
    links:
      - database
    restart: on-failure:50
    volumes:
      - ./code/webroot/sites:/src/webroot/sites:rw

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  flyttilfavrskov:
