version: "3.3"

services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - favrskov-grundsalg:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=$DATABASE_SCHEMA
      - MYSQL_USER=$DATABASE_USER
      - MYSQL_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD
    restart: always
    ports:
      - "3306:3306"

  app:
    image: favrskov-grundsalg:dev
    build:
      context: .
    depends_on:
      - database
    environment:
      - APP_ENV=$ENV
      - DATABASE_URL=$DATABASE_URL
      - DB_HOST=$DATABASE_HOST
      - DB_SCHEMA=$DATABASE_SCHEMA
      - DB_USER=$DATABASE_USER
      - DB_PASS=$DATABASE_PASSWORD
    ports:
      - "8081:80"
    volumes:
      - ./code/webroot:/src/webroot:ro
      - ./code/webroot/sites:/src/webroot/sites:rw
      - ./code/config:/src/config:ro
      - ./code/scripts:/src/scripts:ro
    links:
      - database
    restart: on-failure:50

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  favrskov-grundsalg:
