label: Mediebibliotek
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: 'Tilføj filtre'
          reset_button_label: Gendan
          exposed_sorts_label: 'Sortér efter'
          sort_asc_label: Stigende
          sort_desc_label: Faldende
      pager:
        options:
          expose:
            items_per_page_label: 'Antal elementer'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskydning
          tags:
            previous: ‹‹
            next: ››
      fields:
        media_bulk_form:
          action_title: Handling
      filters:
        status:
          expose:
            label: Publiceringsstatus
          group_info:
            label: Publiceret
            group_items:
              1:
                title: Publiceret
              2:
                title: Afpubliceret
        name:
          expose:
            label: Name
        bundle:
          expose:
            label: 'Medie type'
          group_info:
            label: 'Medie type'
        langcode:
          expose:
            label: Sprog
      sorts:
        created:
          expose:
            label: 'Nyeste først'
        name:
          expose:
            label: 'Navn (A-Z)'
        name_1:
          expose:
            label: 'Navn (Z-A)'
      title: Media
      empty:
        area_text_custom:
          content: 'Ingen tilgængelige media'
  page:
    display_title: Side
    display_options:
      fields:
        media_bulk_form:
          action_title: Handling
        name:
          separator: ', '
        edit_media:
          text: Redigér
        delete_media:
          text: Slet
  widget:
    display_title: Widget
    display_options:
      filters:
        name:
          expose:
            label: Name
      arguments:
        bundle:
          exception:
            title: Alle
      header:
        display_link_grid:
          label: Gitter
        display_link_table:
          label: Tabel
  widget_table:
    display_title: 'Widget (tabel)'
    display_options:
      fields:
        thumbnail__target_id:
          label: Thumbnail
        name:
          label: Name
        uid:
          label: Forfatter
        changed:
          label: Opdateret
      filters:
        name:
          expose:
            label: Name
      arguments:
        bundle:
          exception:
            title: Alle
      header:
        display_link_grid:
          label: Gitter
        display_link_table:
          label: Tabel
