<?php

use Drupal\Core\Site\Settings;


/**
 * Implements hook_locale_translation_projects_alter().
 */
function ftf_core_locale_translation_projects_alter(&$projects) {
  $module_handler = \Drupal::service('module_handler');
  $path = $module_handler->getModule('ftf_core')->getPath();
  $projects['ftf_core']['info']['interface translation server pattern'] = $path . '/translations/%language.po';
}

/**
 * Layout alter - Change and remove definitions.
 *
 * @param $definitions
 */
function ftf_core_layout_alter(&$definitions) {
  // One column
  $definitions['layout_onecol']->setClass('\Drupal\ftf_core\Plugin\Layout\OneColumnLayout');
  // Two column
  $definitions['layout_twocol_section']->setClass('\Drupal\ftf_core\Plugin\Layout\TwoColumnLayout');
  // Three column
  $definitions['layout_threecol_section']->setClass('\Drupal\ftf_core\Plugin\Layout\ThreeColumnLayout');
}

/**
 * Implements hook_page_attachments().
 */
function ftf_core_page_attachments(array &$attachments) {
  if (Settings::get('ftf_core.enable_cookiebot', TRUE)) {
    $attachments['#attached']['library'][] = 'ftf_core/ftf_core.cookiebot_head';
  }
//  $attachments['#attached']['library'][] = 'ftf_core/ftf_core.cookiebot_body';
}
