---
# Apache
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: application-environment
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: application-environment
      type: secret
  output:
    secret:
      name: akvs-apache
      dataKey: APP_ENV

---
# Drupal
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: application-environment
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: application-environment
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: APP_ENV

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: db-host
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: db-host
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: DB_HOST

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: db-schema
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: db-schema
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: DB_SCHEMA

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: db-user
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: db-user
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: DB_USER

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: db-pass
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: db-pass
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: DB_PASS

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: db-port
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: db-port
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: DB_PORT

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: trusted-host-patterns
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: trusted-host-patterns
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: TRUSTED_HOST_PATTERNS

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: external-domains
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: external-domains
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: EXTERNAL_DOMAINS

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: config-split-development
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: config-split-development
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: CONFIG_SPLIT_DEVELOPMENT

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: slack-error-reporter-webhook-url
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: slack-error-reporter-webhook-url
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: SLACK_ERROR_REPORTER_WEBHOOK_URL

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: elasticsearch-protocol
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: elasticsearch-protocol
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: ELASTICSEARCH_PROTOCOL

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: elasticsearch-host
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: elasticsearch-host
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: ELASTICSEARCH_HOST

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: elasticsearch-port
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: elasticsearch-port
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: ELASTICSEARCH_PORT

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: elasticsearch-user
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: elasticsearch-user
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: ELASTICSEARCH_AUTH_USERNAME

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: elasticsearch-pass
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: elasticsearch-pass
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: ELASTICSEARCH_AUTH_PASSWORD

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: sitemap-domain
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: sitemap-domain
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: SITEMAP_DOMAIN

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: smtp-host
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: smtp-host
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: SMTP_HOST

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: smtp-port
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: smtp-port
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: SMTP_PORT

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: smtp-encryption-mode
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: smtp-encryption-mode
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: SMTP_ENCRYPTION_MODE

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: smtp-auth-username
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: smtp-auth-username
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: SMTP_AUTH_USERNAME

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: smtp-auth-password
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: smtp-auth-password
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: SMTP_AUTH_PASSWORD

---
# New Relic
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: newrelic-project-name
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: newrelic-project-name
      type: secret
  output:
    secret:
      name: akvs-newrelic
      dataKey: NEWRELIC_PROJECT_NAME

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: newrelic-license-key
  namespace: flyttilfavrskov
spec:
  vault:
    name: akv-flyttilfavrskov-sta
    object:
      name: newrelic-license-key
      type: secret
  output:
    secret:
      name: akvs-newrelic
      dataKey: NEWRELIC_LICENSE_KEY

