<?php

use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_locale_translation_projects_alter().
 */
function ftf_parcelling_locale_translation_projects_alter(&$projects) {
  $module_handler = \Drupal::service('module_handler');
  $path = $module_handler->getModule('ftf_parcelling')->getPath();
  $projects['ftf_parcelling']['info']['interface translation server pattern'] = $path . '/translations/%language.po';
}

/**
 * Implements hook_cron().
 */
function ftf_parcelling_cron() {
  /** @var \Drupal\ftf_parcelling\Service\ParcelImportService $parcel_import */
  $parcel_import = \Drupal::service('ftf_parcelling.parcel_import');
  $parcel_import->run();
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ftf_parcelling_preprocess_block(&$variables) {
  if($variables['plugin_id'] == 'field_block:node:parcelling:field_parcelling_parcels') {
    $items = ['available' => [], 'reserved' => [], 'sold' => []];
    $content = $variables['content'];
    $i = 0;
    while (array_key_exists($i, $content)) {
      $paragraph = $content[$i]['#paragraph'];
      $items[$paragraph->field_parcel_status->value][] = $content[$i];
      $i++;
    }
    foreach ($items as $key => $parcels) {
      usort($parcels, function ($a, $b) {
        return strnatcmp($a['#paragraph']->field_parcel_address->value, $b['#paragraph']->field_parcel_address->value);
      });
      $items[$key] = $parcels;
    }
    $variables['items'] = $items;
  }
  if($variables['plugin_id'] == 'field_block:node:parcelling:field_parcelling_identifier') {
    if (isset($variables['content']['#object'])) {
      $node = $variables['content']['#object'];
      $parcelling_id = $node->field_parcelling_identifier->value;
      $parcelling_type = $node->field_parent->entity->field_area_type_identifier->value;
      $parcelling_type = $parcelling_type == 'bolig' ? 'byggegrund' : $parcelling_type;
      $variables['#attached']['library'][] = 'ftf_parcelling/ftf_parcelling.minimap';
      $variables['#attached']['drupalSettings']['ftf_parcelling']['parcelling_type'] = $parcelling_type;
      $variables['#attached']['drupalSettings']['ftf_parcelling']['parcelling_id'] = $parcelling_id;
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ftf_parcelling_preprocess_layout_block__gis_minimap(&$variables) {
  $block = $variables['entity'];
  $map_id = $block->field_gis_minimap_id->value;
  if($map_id) {
    $variables['#attached']['library'][] = 'ftf_parcelling/ftf_parcelling.minimap';
    $variables['#attached']['drupalSettings']['ftf_parcelling']['gis_minimap'][$block->id()] = $map_id;
    $variables['gis_block_id'] = $block->id();
  }

}

/**
 * Implements hook_preprocess_HOOK().
 */
function ftf_parcelling_preprocess_paragraph__parcel(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];
  $variables['parcel_group'] = $paragraph->field_parcel_group->value != '' ? $paragraph->field_parcel_group->value : null;
  $variables['parcel_address'] = $paragraph->field_parcel_address->value;
  $variables['parcel_status'] = $paragraph->field_parcel_status->value;
  $variables['parcel_price'] = $paragraph->field_parcel_price->value > 0 ? $paragraph->field_parcel_price->value : null;
  $variables['parcel_min_price'] = $paragraph->field_parcel_min_price->value > 0 ? $paragraph->field_parcel_min_price->value : null;
  $variables['parcel_sqm_price'] = $paragraph->field_parcel_price_sqm->value != '' ? $paragraph->field_parcel_price_sqm->value : null;
  $variables['parcel_area'] = $paragraph->field_parcel_area->value;
  $variables['parcel_type'] = $paragraph->field_parcel_type->value;

  /** @var \Drupal\media\Entity\Media $media_file */
  $media_file = $paragraph->field_parcel_specs->entity;
  if($media_file) {
    $variables['parcel_specs'] = [
      'title' => $media_file->label(),
      'url' => Url::fromUri($media_file->field_media_file->entity->url())->toString(),
      'icon' => 'document',
    ];
  }
}
