label: 'Planlagt indhold'
description: 'Find og håndtér planlagt indhold'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Gendan
          exposed_sorts_label: 'Sortér efter'
          sort_asc_label: Stigende
          sort_desc_label: Faldende
      pager:
        options:
          tags:
            previous: '‹ forrige'
            next: 'næste ›'
            first: '« første'
            last: 'sidste »'
      fields:
        node_bulk_form:
          action_title: Handling
        title:
          label: Title
          separator: ', '
        type:
          label: Indholdstype
          separator: ', '
        name:
          label: Author
          separator: ', '
        status:
          label: Status
          settings:
            format_custom_true: Published
            format_custom_false: Unpublished
          separator: ', '
        publish_on:
          label: 'Udgiv den'
          separator: ', '
        unpublish_on:
          label: 'Afpublicér den'
          separator: ', '
        operations:
          label: Operations
      filters:
        title:
          expose:
            label: Title
        type:
          expose:
            label: 'Content type'
        status:
          expose:
            label: Status
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        langcode:
          expose:
            label: Language
      title: 'Planlagt indhold'
      empty:
        area_text_custom:
          content: 'Intet planlagt indhold'
    display_title: Master
  overview:
    display_options:
      menu:
        title: Planlagt
      tab_options:
        title: Indhold
        description: 'Find og håndtér planlagt indhold'
      display_description: 'Oversigt over alt planlagt indhold, som en fane på hoved ‘indhold admin’ siden'
      display_comment: 'Revision nid forbindelse er påkrævet fordi indholdstypen kun gemmes på ‘indhold’ niveau, ikke ‘indhold revision’ niveau.'
    display_title: 'Indhold oversigt'
  user_page:
    display_options:
      menu:
        title: Planlagt
      tab_options:
        title: Indhold
        description: 'Find og håndtér planlagt indhold'
      display_description: 'Planlagt indhold fane på brugerprofilen, der kun viser brugerens planlagte indhold'
      arguments:
        uid:
          exception:
            title: Alle
      empty:
        area_text_custom:
          content: 'Intet planlagt indhold for bruger {{ arguments.uid }}'
    display_title: 'Brugerprofil fane'
