label: Media
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Gendan
          exposed_sorts_label: 'Sortér efter'
          sort_asc_label: Stigende
          sort_desc_label: Faldende
      pager:
        options:
          expose:
            items_per_page_label: 'Antal elementer'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskydning
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      fields:
        media_bulk_form:
          action_title: Handling
        thumbnail__target_id:
          label: Thumbnail
          separator: ', '
        name:
          label: Medienavn
          separator: ', '
        bundle:
          label: Type
          separator: ', '
        uid:
          label: Author
          separator: ', '
        status:
          label: Status
          settings:
            format_custom_true: Published
            format_custom_false: Unpublished
          separator: ', '
        changed:
          label: Opdateret
          separator: ', '
        operations:
          label: Operations
      filters:
        name:
          expose:
            label: Medienavn
        bundle:
          expose:
            label: Type
        status:
          expose:
            label: Sandt
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        langcode:
          expose:
            label: Language
      title: Media
      empty:
        area_text_custom:
          content: 'Ingen tilgængelige media'
  media_page_list:
    display_title: Media
    display_options:
      menu:
        title: Media
