label: Ordliste
description: 'Alt indhold efter forbogstav.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Udfør
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Antal elementer'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskydning
          tags:
            previous: ‹‹
            next: ››
      fields:
        title:
          label: Title
        name:
          label: Author
        changed:
          label: 'Seneste opdatering'
  attachment_1:
    display_title: Bilag
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Ordliste
