label: 'Hvem er online'
description: 'Viser navnene på de brugere, der senste har været aktive, og det totale antal af aktive brugere.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Udfør
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      filters:
        access:
          expose:
            label: 'Seneste tilgang'
            description: 'En bruger bliver opfattet som online i dette tidsrum efter hun sidst har set en side.'
      title: 'Hvem er online'
      header:
        result:
          content: 'Der er i øjeblikket @total brugere online.'
      empty:
        area_text_custom:
          content: 'Der er i øjeblikket 0 brugere online.'
  who_s_online_block:
    display_title: 'Hvem er online'
    display_options:
      block_description: 'Hvem er online'
      display_description: 'En liste af indloggede brugere.'
