label: 'Ord i ordforråd'
description: 'Indhold som er knyttet til en bestemt term.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Udfør
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Antal elementer'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskydning
          tags:
            previous: ‹‹
            next: ››
      arguments:
        tid:
          exception:
            title: Alle
          title: '{{ arguments.tid }}'
  feed_1:
    display_title: Feed
  page_1:
    display_title: Page
