label: Indhold
description: 'Find og håndtér indhold.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      fields:
        title:
          label: Title
        type:
          label: 'Content type'
          separator: ', '
        name:
          label: Author
        status:
          label: Status
          settings:
            format_custom_true: Published
            format_custom_false: Unpublished
        changed:
          label: Opdateret
        operations:
          label: Operations
      filters:
        title:
          expose:
            label: Title
        type:
          expose:
            label: 'Content type'
        status:
          expose:
            label: Status
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        langcode:
          expose:
            label: Language
      title: Indhold
      empty:
        area_text_custom:
          content: 'Der blev ikke fundet noget indhold'
    display_title: Master
  page_1:
    display_options:
      menu:
        title: Indhold
      tab_options:
        title: Indhold
        description: 'Find og håndtér indhold'
    display_title: Page
