label: Mediebibliotek
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: 'Tilføj filtre'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Antal elementer'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskydning
          tags:
            previous: ‹‹
            next: ››
      fields:
        media_bulk_form:
          action_title: Handling
      filters:
        status:
          expose:
            label: Publiceringsstatus
          group_info:
            label: Published
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        name:
          expose:
            label: Name
        bundle:
          expose:
            label: 'Medie type'
          group_info:
            label: 'Medie type'
        langcode:
          expose:
            label: Language
      sorts:
        created:
          expose:
            label: 'Nyeste først'
        name:
          expose:
            label: 'Navn (A-Z)'
        name_1:
          expose:
            label: 'Navn (Z-A)'
      title: Media
      empty:
        area_text_custom:
          content: 'Ingen tilgængelige media'
  page:
    display_title: Page
    display_options:
      fields:
        media_bulk_form:
          action_title: Handling
        name:
          separator: ', '
        edit_media:
          text: Redigér
        delete_media:
          text: Slet
  widget:
    display_title: Widget
    display_options:
      filters:
        name:
          expose:
            label: Name
      arguments:
        bundle:
          exception:
            title: Alle
      header:
        display_link_grid:
          label: Gitter
        display_link_table:
          label: Tabel
  widget_table:
    display_title: 'Widget (tabel)'
    display_options:
      fields:
        thumbnail__target_id:
          label: Thumbnail
        name:
          label: Name
        uid:
          label: Author
        changed:
          label: Opdateret
      filters:
        name:
          expose:
            label: Name
      arguments:
        bundle:
          exception:
            title: Alle
      header:
        display_link_grid:
          label: Gitter
        display_link_table:
          label: Tabel
