label: 'Nye brugere'
description: 'Viser en liste af de nyeste brugerkonti på sitet.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Udfør
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      title: 'Nye brugere'
  block_1:
    display_title: 'Nye brugere'
    display_options:
      display_description: 'En liste af nye brugere'
      block_description: 'Nye brugere'
      block_category: Bruger
