label: 'Medie bibliotek (DDS)'
description: ''
display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Gendan
          exposed_sorts_label: 'Sortér efter'
          sort_asc_label: Stigende
          sort_desc_label: Faldende
      pager:
        options:
          tags:
            first: '« Første'
            last: 'Sidste »'
          expose:
            items_per_page_label: 'Antal elementer'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskydning
      fields:
        thumbnail__target_id: {  }
        name: {  }
      filters:
        bundle:
          expose:
            label: 'Medie type'
        field_media_category_target_id:
          expose:
            label: 'Medie kategori'
      title: 'Medie bibliotek (DDS)'
