label: Nyheder
description: 'Find og administrér nyhedsartikler'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Forrige'
            next: 'Næste ›'
            first: '« Første'
            last: 'Sidste »'
      fields:
        title:
          label: Titel
        name:
          label: Forfatter
        status:
          label: Status
          settings:
            format_custom_true: Publiceret
            format_custom_false: Afpubliceret
        changed:
          label: Opdateret
        operations:
          label: Handlinger
      filters:
        title:
          expose:
            label: Titel
        type:
          expose:
            label: Indholdstype
        status:
          expose:
            label: Status
          group_info:
            label: 'Publiceret status'
            group_items:
              1:
                title: Publiceret
              2:
                title: Afpubliceret
        langcode:
          expose:
            label: Sprog
      title: Indhold
      empty:
        area_text_custom:
          content: 'Der blev ikke fundet noget indhold'
    display_title: Master
  page_1:
    display_options:
      menu:
        title: Nyheder
      tab_options:
        title: Nyheder
        description: 'Find og administrér nyhedsartikler'
    display_title: Side
