display:
  default:
    display_options:
      fields:
        node_bulk_form:
          label: ''
        title:
          label: Titel
        name:
          label: Forfatter
        status:
          label: Status
          settings:
            format_custom_true: Udgivet
            format_custom_false: 'Ikke udgivet'
        changed:
          label: Opdateret
        operations:
          label: Handlinger
      filters:
        title:
          expose:
            description: ''
            label: Titel
          group_info:
            label: ''
            description: ''
        type:
          expose:
            description: ''
            label: Indholdstype
          group_info:
            label: ''
            description: ''
        status:
          expose:
            description: ''
            label: Status
          group_info:
            description: ''
            label: 'Udgivelses status'
            group_items:
              1:
                title: Udgivet
              2:
                title: 'Ikke udgivet'
        langcode:
          expose:
            description: ''
            label: Sprog
          group_info:
            label: ''
            description: ''
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Nulstil
          exposed_sorts_label: 'Sorter efter'
          sort_asc_label: Stigende
          sort_desc_label: Faldende
      pager:
        options:
          tags:
            previous: '‹ Forrige'
            next: 'Næste ›'
            first: '« Første'
            last: 'Sidste »'
      title: Nyheder
      empty:
        area_text_custom:
          content: 'Intet tilgængeligt indhold'
    display_title: Master
  page_1:
    display_options:
      menu:
        description: ''
        title: Nyheder
      tab_options:
        title: Nyheder
        description: 'Find og administrer nyheder'
    display_title: Side
label: Nyheder
description: 'Find and administrer nyheder.'
