---
apiVersion: v1
kind: ConfigMap

metadata:
  name: php-env
  namespace: flyttilfavrskov
data:
  MEMCACHED_HOST: ""
  REDIS_HOST: redis-transient-single-service
  INTERNAL_DOMAIN: website-php-svc

---
apiVersion: v1
kind: ConfigMap

metadata:
  name: apache-env
  namespace: flyttilfavrskov
data:
  PHP_CONTAINER_NAME: website-php-svc

