.base: &base
  roles: app
  branch: develop
  user: favrskov
  hostname: flyttilfavrskov.dk

prod:
  <<: *base
  stage: production
  deploy_path: /var/www/flyttilfavrskov.dk
  branch: master
  hostname: 81.95.247.233

stage:
  <<: *base
  stage: develop
  deploy_path: /data/www/vhost/staging.flyttilfavrskov.drupal.dk
  hostname: 81.95.247.111
  branch: develop
