---
apiVersion: batch/v1beta1
kind: CronJob

metadata:
  name: website-cron
  namespace: flyttilfavrskov
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            "kubernetes.io/os": linux

          volumes:
            - name: files-public-azfp
              persistentVolumeClaim:
                claimName: files-public-azfp-pvc

            - name: files-private-azf
              persistentVolumeClaim:
                claimName: files-private-azf-pvc

            - name: files-cache
              persistentVolumeClaim:
                claimName: files-cache-longhorn-pvc

          containers:
          - name: php
            image: acrfavrskov.azurecr.io/flyttilfavrskov-php:0.1.4
#            ports:
#              - containerPort: 9001
            securityContext:
              runAsUser: 0
              privileged: true
              capabilities:
                add:
                  - SYS_ADMIN # Enabled to bind mounts correctly

            resources:
              requests:
                cpu: 250m
                memory: 1024Mi

            volumeMounts:
              - name: files-public-azfp
                mountPath: /app/webroot/sites/flyttilfavrskov.dk/files

              - name: files-private-azf
                mountPath: /app/private-files

              - name: files-cache
                mountPath: /mnt/cache
                subPath: cache # Store under cache subdir on mounted storage

            envFrom:
              - configMapRef:
                  name: php-env
              - secretRef:
                  name: akvs-drupal
              - secretRef:
                  name: akvs-newrelic

            command: ["/release/entrypoint.cron.sh"]

          restartPolicy: OnFailure
