module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  allowed_formats: 0
  automated_cron: 0
  autosave_form: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  contact: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  dbal: 0
  dds_content: 0
  dds_content_hierarchy: 0
  dds_content_hierarchy_breadcrumb: 0
  dds_content_hierarchy_path: 0
  dds_editor_manual: 0
  dds_editors: 0
  dds_elasticsearch: 0
  dds_entity_data: 0
  dds_layout_block_accordion: 0
  dds_layout_block_appetizer: 0
  dds_layout_block_button: 0
  dds_layout_block_divider: 0
  dds_layout_block_hero: 0
  dds_layout_block_image: 0
  dds_layout_block_inline_navigation: 0
  dds_layout_block_mailchimp: 0
  dds_layout_block_news_list: 0
  dds_layout_block_quote: 0
  dds_layout_block_rte: 0
  dds_layout_block_slideshow: 0
  dds_layout_block_video: 0
  dds_layouts: 0
  dds_media: 0
  dds_news: 0
  dds_search: 0
  dds_seo: 0
  dds_site_settings: 0
  dynamic_page_cache: 0
  editor: 0
  elasticsearch_connector: 0
  entity_clone: 0
  entity_hierarchy: 0
  entity_hierarchy_breadcrumb: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  ftf_parcelling: 0
  gtm: 0
  help: 0
  history: 0
  hreflang: 0
  image: 0
  inline_block_title_automatic: 0
  language: 0
  layout_builder: 0
  layout_builder_modal: 0
  layout_discovery: 0
  link: 0
  locale: 0
  mailchimp: 0
  mailchimp_lists: 0
  mailchimp_signup: 0
  media: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  monolog: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  role_delegation: 0
  scheduler: 0
  search_api: 0
  search_api_exclude_entity: 0
  shortcut: 0
  simple_sitemap: 0
  site_settings: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  view_unpublished: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  dds_layout_blocks: 100
  dds_premium_installer: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  dds_premium: 0
profile: dds_premium_installer
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
